id = "whkd"
name = "whkd"
version = "0.1.0"
schema_version = 1
authors = ["LGUG2Z <lgug2z@fastmail.com>"]
description = "Tree-sitter syntax highlighting for whkd"
repository = "https://github.com/LGUG2Z/zed-whkd"

[grammars.whkd]
repository = "https://github.com/LGUG2Z/tree-sitter-whkd"
commit = "2ad0e8aeb9f4dad732f77cd44666f7bbf0bb3a2d"
